modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved unless otherwise explicitly stated"

[[mods]]
modId="swplanets"
version="1.3"
displayName="Star Wars Planets"
displayURL="https://www.curseforge.com/minecraft/mc-mods/star-wars-planets"
logoFile="logo.png"
authors="TATHAN"
description='''
This Mod is a Addon for Beyond Earth.
It add planets from Star Wars !
'''

[[dependencies.swplanets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.swplanets]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.52,]"
    ordering="NONE"
    side="BOTH"