modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/TathanDev/StarWarsPlanets/issues"
license="All Rights Reserved unless otherwise explicitly stated"

[[mods]]
modId="swplanets"
version="1.9"
displayName="Star Wars Planets"
displayURL="https://www.curseforge.com/minecraft/mc-mods/star-wars-planets"
logoFile="logo.png"
credits="Yettai_Yogenhiem, TheRealM18, MrScautHD"
authors="TATHAN"
description='''
This Mod is a Addon for Beyond Earth.
It add planets from Star Wars and Light Saber :)
'''

[[dependencies.swplanets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.swplanets]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.52,]"
    ordering="NONE"
    side="BOTH"