blank_issues_enabled: false
contact_links:
  - name: Beyond Earth Discord
    url: https://discord.gg/qvsUKZUX
    about: Join our Discord for support, questions, discussion. You can ping me if you want help @TATHAN