blank_issues_enabled: false
contact_links:
  - name: Odysseyus Studio Discord
    url: https://discord.gg/nuDEYcFX4j
    about: Join our Discord for support, questions, discussion. You can ping me if you want help @TATHAN
